ALTER TABLE SPLIT_BILL_MEMBER
MODIFY (id VARCHAR2(36));

ALTER TABLE SPLIT_BILL
MODIFY (id VARCHAR2(36));

ALTER TABLE ACCOUNT
MODIFY (id VARCHAR2(36));

ALTER TABLE PROFILE
MODIFY (id VARCHAR2(36));

ALTER TABLE TRX_HISTORY
MODIFY (id VARCHAR2(36));

ALTER TABLE TRX_CATEGORY
MODIFY (id VARCHAR2(36));

ALTER TABLE CARD_PRODUCT
MODIFY (id VARCHAR2(36));

ALTER TABLE LIFEGOALS_ACCOUNT
MODIFY (id VARCHAR2(36));

ALTER TABLE DPLK_ACCOUNT
MODIFY (id VARCHAR2(36));

ALTER TABLE OTP_VERIFICATION
MODIFY (id VARCHAR2(36));

ALTER TABLE TIME_DEPOSIT_ACCOUNT
MODIFY (id VARCHAR2(36));

ALTER TABLE OTP_VERIFICATION
MODIFY (id VARCHAR2(36));