spring:
  application:
    name: wandoor

  datasource:
    url: "jdbc:oracle:thin:@localhost:1521/WANDOOR_DB"
    username: ${DB_USERNAME:WANDOOR}
    password: ${DB_PASSWORD:root}
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
    open-in-view: false

  flyway:
    enabled: true
    default-schema: WANDOOR
    schemas: WANDOOR
    create-schemas: false
    locations: classpath:db/migration

  mail:
    host: smtp.gmail.com
    port: 587
    username: oktaviaq.a@gmail.com
    password: ywia odzr xmbk jbex
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.data.redis: INFO

# secret & expiry JWT
app:
  jwt:
    secret: ${JWT_SECRET:MySuperSecretKeyForBankingApp}
    expiration-ms: 3600000

server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never

spring.redis.host=localhost     # Host Redis (misalnya, localhost jika Redis ada di mesin yang sama)
spring.redis.port=6379          # Port Redis (default: 6379)
spring.redis.password=          # Jika Redis memerlukan password, masukkan di sini (kosongkan jika tidak ada)
spring.redis.timeout=2000       # Timeout koneksi dalam milidetik
spring.cache.type=redis         # Menggunakan Redis untuk caching